import { NextRequest, NextResponse } from 'next/server'
import { verifyConfToken } from '@/lib/paymentToken'

// Browser → GET /api/payment/status?id=<id>&t=<sig>&te=<exp> → bridge.php get_stagiaire_status.
//
// SECURITY:
// - Requires a valid, UNEXPIRED conf token (HMAC over `<id>|conf|<exp>` with the conf
//   subkey), generated by PSP's twelvy_validate.php. Without it → 403. Stops IDOR
//   enumeration of all stagiaires.
// - Returns only an ALLOWLIST of non-sensitive fields (status + prénom + ref + stage
//   recap). Email and full name are NOT forwarded to the browser even on success.
// - X-Api-Key for the bridge stays server-side. no-store + no-referrer.

const BRIDGE_URL = process.env.BRIDGE_URL || 'https://api.twelvy.net/bridge.php'
const BRIDGE_API_KEY = process.env.BRIDGE_API_KEY || ''

const SECURITY_HEADERS = {
  'Cache-Control': 'no-store',
  'Referrer-Policy': 'no-referrer',
}

export async function GET(request: NextRequest) {
  if (!BRIDGE_API_KEY) {
    return NextResponse.json(
      { success: false, error: { code: 'config_error', message: 'Bridge API key not configured' } },
      { status: 500, headers: SECURITY_HEADERS }
    )
  }

  const { searchParams } = new URL(request.url)
  const id = Number(searchParams.get('id') || '')
  const sig = searchParams.get('t') || ''
  const exp = searchParams.get('te') || ''

  if (!Number.isInteger(id) || id <= 0) {
    return NextResponse.json(
      { success: false, error: { code: 'invalid_id', message: 'Identifiant invalide' } },
      { status: 400, headers: SECURITY_HEADERS }
    )
  }
  if (!verifyConfToken(id, sig, exp, BRIDGE_API_KEY)) {
    return NextResponse.json(
      { success: false, error: { code: 'forbidden', message: 'Accès non autorisé ou expiré' } },
      { status: 403, headers: SECURITY_HEADERS }
    )
  }

  try {
    const response = await fetch(`${BRIDGE_URL}?action=get_stagiaire_status`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Api-Key': BRIDGE_API_KEY },
      body: JSON.stringify({ stagiaire_id: id }),
    })
    const data = await response.json()

    if (!response.ok || !data?.success) {
      return NextResponse.json(
        { success: false, error: { code: 'status_unavailable', message: 'Statut indisponible' } },
        { status: response.status === 404 ? 404 : 502, headers: SECURITY_HEADERS }
      )
    }

    // Allowlist projection — never forward email/nom to the browser.
    const d = data.data || {}
    const st = d.stage || {}
    const projected = {
      success: true,
      data: {
        status: d.status, // paye | refuse | en_attente
        prenom: d.stagiaire?.prenom,
        facture_num: d.stagiaire?.facture_num,
        montant_total: d.stagiaire?.montant_total, // base + Garantie Sérénité (what was actually paid)
        total_guarantee: d.stagiaire?.total_guarantee,
        errorCategory: d.errorCategory,
        errorMessage: d.errorMessage,
        stage: {
          date_debut: st.date_debut,
          date_fin: st.date_fin,
          prix: st.prix,
          lieu_nom: st.lieu_nom,
          lieu_ville: st.lieu_ville,
          lieu_cp: st.lieu_cp,
        },
      },
    }
    return NextResponse.json(projected, { status: 200, headers: SECURITY_HEADERS })
  } catch (error) {
    console.error('status proxy error:', error)
    return NextResponse.json(
      { success: false, error: { code: 'proxy_error', message: 'Service indisponible' } },
      { status: 502, headers: SECURITY_HEADERS }
    )
  }
}
